import { createFileRoute } from '@tanstack/react-router'
import { ArrowUpRight, Check, ChevronDown, Menu, Sparkles, Star, X } from 'lucide-react'
import { useState } from 'react'

export const Route = createFileRoute('/')({ component: Home })

const plans = [
  { name: 'Starter', price: '$249', copy: 'A polished sticker starter pack for solo agents.', items: ['3 custom animated stickers', 'GIPHY submission & verification', 'One revision round'] },
  { name: 'Signature', price: '$499', copy: 'The complete branded toolkit for agents who want to stand out.', items: ['7 custom animated stickers', 'GIPHY submission & verification', 'Two revision rounds', 'Social usage guide'], featured: true },
  { name: 'Team', price: '$899', copy: 'A shared visual language for your whole brokerage.', items: ['15 custom animated stickers', 'GIPHY brand channel setup', 'Unlimited revisions for 30 days', 'Team rollout guide'] },
]

function Home() {
  const [mobile, setMobile] = useState(false)
  const [openFaq, setOpenFaq] = useState(0)
  const faqs = ['What exactly do I get?', 'How long does it take?', 'Can I use my stickers anywhere?', 'What does GIPHY verification mean?']
  return <div className="site">
    <header className="nav wrap"><a className="logo" href="#top"><b>✦</b> realtor<span>stickers</span></a><button className="menu" onClick={() => setMobile(!mobile)} aria-label="Menu">{mobile ? <X /> : <Menu />}</button><nav className={mobile ? 'open' : ''}><a href="#work">See the work</a><a href="#process">How it works</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a><a className="nav-cta" href="#contact">Start a project <ArrowUpRight size={15}/></a></nav></header>
    <main id="top">
      <section className="hero wrap"><div><div className="eyebrow"><Sparkles size={14}/> Motion for the modern agent</div><h1>Your brand,<br/><em>everywhere.</em></h1><p className="lead">Custom animated stickers that make your real estate brand impossible to ignore — on Instagram, in texts, and everywhere your clients are.</p><div className="actions"><a className="button dark" href="#contact">Make my stickers <ArrowUpRight size={17}/></a><a className="watch" href="#work">▶ &nbsp; Watch the reel</a></div><div className="proof"><span>J</span><span>M</span><span>A</span><strong>Loved by 120+ agents</strong> <i>★★★★★</i></div></div><div className="hero-art"><div className="sun"/><div className="poster back">JUST<br/>LISTED</div><div className="poster front"><small>YOUR BRAND IN MOTION</small><div>⌂</div><p>Keys to<br/><b>your next chapter</b></p></div><div className="floating mint">NEW<br/>HOME</div><p className="caption">GIFs that feel<br/><b>like you.</b></p></div></section>
      <div className="marquee">GIPHY VERIFIED　✦　AGENT APPROVED　✦　MADE TO SHARE　✦　GIPHY VERIFIED</div>
      <section id="work" className="wrap section"><div className="section-head"><div><div className="eyebrow">01 / The work</div><h2>Small pixels.<br/><em>Big presence.</em></h2></div><p>Not generic templates. We turn the things that make your business yours into a sticker set your clients actually want to use.</p></div><div className="gallery"><article className="tile peach"><small>FOR THE BIG REVEAL</small><div className="stamp">SOLD<br/><i>✦ ✦ ✦</i></div><b className="sticker yellow">SOLD</b></article><article className="tile green"><small>FOR THE DAILY GRIND</small><div className="coffee">☕</div><h3>But first,<br/><em>coffee.</em></h3><b className="sticker pink">LET'S<br/>CHAT</b></article><article className="tile lilac"><small>FOR YOUR SIGNATURE</small><div className="signature">Alex<br/><i>Realtor</i></div><b className="sticker purple">THAT'S<br/>A WRAP</b></article></div></section>
      <section id="process" className="wrap process"><div className="eyebrow">02 / The process</div><h2>From idea to <em>iconic.</em></h2><div className="steps"><Step n="01" title="Find your flavor">We pull out the phrases, quirks, and tiny details that make your brand memorable.</Step><Step n="02" title="Make it move">Our designers turn your ideas into playful, polished motion that looks great everywhere.</Step><Step n="03" title="Get verified">We submit your set to GIPHY, so clients can find and share your stickers in seconds.</Step></div></section>
      <section className="giphy"><div className="wrap giphy-inner"><div className="g">G</div><div><div className="eyebrow">The GIPHY advantage</div><h2>Don’t just send a GIF.<br/><em>Be the GIF.</em></h2><p>We handle verification from start to finish. Your stickers become searchable on GIPHY — putting your brand one tap away from every conversation.</p><a className="light-link" href="#contact">Get GIPHY verified <ArrowUpRight size={16}/></a></div><div className="search-demo"><div className="search">⌕　Alex the Realtor</div><div className="result"><b>✦</b><span><strong>Alex the Realtor</strong><small>Official Sticker Collection</small></span><Check size={18}/></div><div className="result faded"><b>♥</b><span><strong>Your brand, here</strong><small>Shared by your clients</small></span></div></div></div></section>
      <section id="pricing" className="wrap section"><div className="section-head"><div><div className="eyebrow">03 / Simple pricing</div><h2>Pick your<br/><em>personality.</em></h2></div><p>One-time investment. A lifetime of being the agent people remember. Every package includes strategy, design, and delivery-ready files.</p></div><div className="plans">{plans.map(plan => <article className={plan.featured ? 'plan featured' : 'plan'} key={plan.name}>{plan.featured && <label>Most popular</label>}<h3>{plan.name}</h3><p>{plan.copy}</p><div className="price">{plan.price}<small> / project</small></div><ul>{plan.items.map(item => <li key={item}><Check size={16}/>{item}</li>)}</ul><a className={plan.featured ? 'button dark' : 'button outline'} href="#contact">Choose {plan.name} <ArrowUpRight size={16}/></a></article>)}</div></section>
      <section id="faq" className="faq wrap"><div><div className="eyebrow">04 / Good to know</div><h2>Questions,<br/><em>answered.</em></h2></div><div>{faqs.map((question, i) => <div className="faq-row" key={question}><button onClick={() => setOpenFaq(openFaq === i ? -1 : i)}><span>0{i + 1}　{question}</span><ChevronDown className={openFaq === i ? 'rotate' : ''}/></button>{openFaq === i && <p>Every project is made from scratch around your brand. We share a private review link, refine the set with you, and deliver ready-to-use GIF files plus your GIPHY link.</p>}</div>)}</div></section>
      <section id="contact" className="contact"><div className="wrap"><div className="eyebrow">Ready when you are</div><h2>Make your mark<br/><em>in motion.</em></h2><p>Tell us a little about your brand. We’ll be in touch within two business days.</p><a className="button dark" href="mailto:hello@realtorstickers.com">Start a project <ArrowUpRight size={18}/></a></div></section>
    </main><footer className="footer wrap"><a className="logo" href="#top"><b>✦</b> realtor<span>stickers</span></a><span>© 2025 RealtorStickers</span><span><a href="#contact">Instagram</a>　<a href="mailto:hello@realtorstickers.com">Contact</a></span></footer>
  </div>
}
function Step({ n, title, children }: { n: string; title: string; children: string }) { return <div className="step"><small>{n}</small><Star size={18}/><h3>{title}</h3><p>{children}</p></div> }
